import React from 'react';
import { Link } from 'react-router-dom';
import { Shield, Lock, ArrowLeft } from 'lucide-react';

const GRAD = '#5B3FD6';
const GRAD2 = '#8B5CF6';

const sections = [
  {
    title: '1. Information We Collect',
    blocks: [
      {
        subtitle: '1.1 Information You Provide',
        items: [
          'Account information: name, email address, password (stored hashed), organization/team affiliation, and role (admin, editor, viewer).',
          'Meeting content: audio and video files, uploaded transcripts, and any text you enter (e.g., meeting titles, notes, edits to action items).',
          'Communications: support requests or other messages you send us.',
        ],
      },
      {
        subtitle: '1.2 Information Generated by the Service',
        items: [
          'Transcriptions generated from your uploaded audio/video.',
          'AI-generated outputs: summaries, key discussion points, extracted action items, ownership/deadline assignments, and sentiment or productivity analytics.',
          'Usage data: task completion rates, meeting effectiveness metrics, and productivity trends associated with your account or team.',
        ],
      },
      {
        subtitle: '1.3 Information from Integrations',
        items: [
          'If you connect Google Calendar, we collect the OAuth tokens and calendar data (such as event details) necessary to create events and sync scheduling, limited to the scopes you authorize (e.g., calendar.events, basic profile info). We do not access Google data beyond what is needed for this integration.',
        ],
      },
      {
        subtitle: '1.4 Automatically Collected Information',
        items: [
          'Standard technical data such as IP address, browser type, device information, and log data (e.g., login timestamps, API request logs) collected for security, rate-limiting, and diagnostic purposes.',
        ],
      },
    ],
  },
  {
    title: '2. How We Use Information',
    items: [
      'Provide core Service functionality: transcription, summarization, action-item extraction, and analytics.',
      'Authenticate and secure your account (JWT-based sessions, rate limiting).',
      'Operate role-based access controls within your team/workspace.',
      'Sync with Google Calendar where you have enabled that integration.',
      'Send service-related notifications (e.g., overdue task alerts, weekly productivity reports).',
      'Maintain, debug, and improve the Service.',
      'Comply with legal obligations and enforce our Terms and Conditions.',
      'We do not sell your personal information or meeting content.',
    ],
  },
  {
    title: '3. AI Processing and Third-Party Sub-Processors',
    items: [
      'To generate transcriptions and analysis, Meetiva transmits relevant portions of your uploaded content to third-party AI providers that perform speech-to-text transcription and natural-language analysis to produce summaries, action items, and other AI-generated insights.',
      'These providers act as sub-processors and process data under contractual terms consistent with this Policy. They do not use your content to train their own general-purpose models beyond what is disclosed in our sub-processor agreements.',
    ],
  },
  {
    title: '4. Legal Basis for Processing (GDPR)',
    items: [
      'Contract necessity: to provide the Service you have signed up for.',
      'Legitimate interests: to secure, maintain, and improve the Service.',
      'Consent: for optional integrations (e.g., Google Calendar) and certain communications.',
      'Legal obligation: where required by applicable law.',
    ],
  },
  {
    title: '4A. Compliance with India\'s DPDP Act, 2023',
    items: [
      'Where you access the Service from India, Meetiva acts as a "Data Fiduciary" and you are a "Data Principal" under the Digital Personal Data Protection Act, 2023.',
      'Notice and Consent: Before processing your personal data, we provide notice describing what is collected and the purpose, in clear and plain language. Your consent must be free, specific, informed, unconditional, and given through clear affirmative action. You may withdraw consent at any time through your account settings.',
      'Your Rights as a Data Principal: obtain a summary of personal data held, request correction and updating, request erasure once the purpose is no longer served, have grievances addressed before approaching the Data Protection Board of India, and nominate another individual to exercise these rights.',
      'Grievance Officer: Vaibhav Darji (vaibhavya0510@gmail.com) — designated to address complaints and requests under the DPDP Act. We aim to respond within 30 days.',
      'Data Breach Notification: In the event of a personal data breach, we will notify the Data Protection Board of India and affected Data Principals as required.',
    ],
  },
  {
    title: '5. Data Storage and Security',
    items: [
      'Data is stored in MongoDB Atlas with access restricted by role-based permissions.',
      'AES-256 encryption at rest and TLS 1.3 encryption in transit.',
      'Session and rate-limiting data is managed via Redis and is not used for long-term profiling.',
      'OAuth tokens (e.g., Google Calendar) are encrypted at rest.',
      'No method of transmission or storage is 100% secure; we cannot guarantee absolute security.',
    ],
  },
  {
    title: '6. Data Retention',
    items: [
      'We retain meeting content, transcriptions, and AI-generated outputs for as long as your account is active or as needed to provide the Service, unless you delete specific meetings or your account.',
    ],
  },
  {
    title: '7. Your Rights and Choices',
    items: [
      'Access, correct, or delete your personal data and meeting content.',
      'Export your data (e.g., summaries, action items).',
      'Withdraw consent for optional integrations (disconnect Google Calendar at any time in Settings).',
      'Object to or restrict certain processing.',
      'Opt out of non-essential notifications (e.g., weekly productivity reports) via account settings.',
      'Lodge a complaint with your local data protection authority (for EU/EEA/UK users).',
    ],
  },
  {
    title: '8. Data Sharing',
    items: [
      'Third-party AI sub-processors (transcription and analysis providers).',
      'Google, when you enable Calendar integration, limited to the authorized scopes.',
      'Your team/organization, since meeting summaries and action items are visible to team members per role-based access settings.',
      'Service providers supporting hosting, infrastructure, and security.',
      'Legal authorities, where required by law or to protect rights, safety, or property.',
      'We do not share your data with third parties for their own marketing purposes.',
    ],
  },
  {
    title: '9. International Data Transfers',
    items: [
      'Meetiva\'s infrastructure is hosted in India. Where sub-processors outside India process data, we apply contractual safeguards consistent with the DPDP Act.',
    ],
  },
  {
    title: '10. Children\'s Privacy',
    items: [
      'Meetiva is intended for use by faculty, students, and professionals and is not directed at children under 16. We do not knowingly collect personal data from children below that age.',
    ],
  },
  {
    title: '11. Meeting Participant Data',
    items: [
      'Meetiva may process voices, names, and statements of individuals who participate in recorded meetings but who are not themselves Meetiva account holders. The account holder who uploads a meeting is responsible for obtaining any necessary consent from participants before uploading.',
      'Participants who wish to request removal of their data may contact privacy.meetiva.ai@gmail.com or the uploading account holder directly.',
    ],
  },
  {
    title: '12. Changes to This Policy',
    items: [
      'We may update this Privacy Policy from time to time. Material changes will be communicated via the Service or by email. The "Last Updated" date reflects the most recent revision.',
    ],
  },
  {
    title: '13. Contact Us',
    items: [
      'For privacy-related questions or requests, contact: privacy.meetiva.ai@gmail.com',
    ],
  },
];

const PrivacyPage: React.FC = () => {
  return (
    <div className="min-h-screen" style={{ background: '#FCFBFF' }}>
      <div className="border-b border-[#E4E0F5] bg-white/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-3">
            <div
              className="w-11 h-11 rounded-2xl flex items-center justify-center text-white font-bold"
              style={{ background: `linear-gradient(135deg, ${GRAD}, ${GRAD2})` }}
            >
              M
            </div>
            <div>
              <p className="text-xs uppercase tracking-[0.28em] text-[#64607A]">Meetiva.ai</p>
              <p className="text-sm font-medium text-[#1D1B22]">Privacy Policy</p>
            </div>
          </Link>
          <Link
            to="/"
            className="flex items-center gap-2 text-sm font-medium text-[#64607A] hover:text-[#1D1B22] transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-10">
        <div className="rounded-[2rem] border border-[#E4E0F5] bg-white p-8 lg:p-10 shadow-sm">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#E4E0F5] bg-[#F5F3FF] px-4 py-2 text-xs font-semibold uppercase tracking-[0.28em]"
            style={{ color: GRAD }}>
            <Shield className="h-3.5 w-3.5" /> Privacy Policy
          </div>
          <h1 className="mt-6 text-4xl font-bold tracking-tight text-[#1D1B22] md:text-5xl">
            Privacy built for a product that listens, summarizes, and acts.
          </h1>
          <p className="mt-5 max-w-3xl text-lg leading-8 text-[#64607A]">
            This Privacy Policy explains how Meetiva collects, uses, discloses, and protects
            information when you use our AI-powered meeting intelligence platform.
          </p>
          <div className="mt-8 grid gap-4 sm:grid-cols-3">
            {[
              ['Last updated', 'September 2026'],
              ['Encryption', 'AES-256 + TLS 1.3'],
              ['Retention', 'User-controlled'],
            ].map(([label, value]) => (
              <div key={label} className="rounded-2xl border border-[#E4E0F5] bg-[#F8F7FF] p-4">
                <p className="text-xs uppercase tracking-[0.24em] text-[#64607A]">{label}</p>
                <p className="mt-2 text-sm font-semibold text-[#1D1B22]">{value}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-8 space-y-6">
          {sections.map((section, index) => (
            <div key={section.title} className="rounded-2xl border border-[#E4E0F5] bg-white p-6 shadow-sm">
              <div className="flex items-start gap-4">
                <div
                  className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl text-white"
                  style={{ background: `linear-gradient(135deg, ${GRAD}, ${GRAD2})` }}
                >
                  <Lock className="h-5 w-5" />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center justify-between gap-4">
                    <h2 className="text-xl font-semibold text-[#1D1B22]">{section.title}</h2>
                    <span
                      className="rounded-full border border-[#E4E0F5] bg-[#F8F7FF] px-3 py-1 text-xs font-semibold"
                      style={{ color: GRAD }}
                    >
                      {String(index + 1).padStart(2, '0')}
                    </span>
                  </div>
                  <div className="mt-4 space-y-3">
                    {section.blocks
                      ? section.blocks.map((block) => (
                          <div key={block.subtitle}>
                            <p className="text-sm font-semibold text-[#1D1B22] mb-2">{block.subtitle}</p>
                            {block.items.map((item) => (
                              <div
                                key={item}
                                className="rounded-2xl border border-[#E4E0F5] bg-[#F8F7FF] p-4 text-sm leading-7 text-[#64607A] mb-2"
                              >
                                {item}
                              </div>
                            ))}
                          </div>
                        ))
                      : section.items?.map((item) => (
                          <div
                            key={item}
                            className="rounded-2xl border border-[#E4E0F5] bg-[#F8F7FF] p-4 text-sm leading-7 text-[#64607A]"
                          >
                            {item}
                          </div>
                        ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-8 rounded-[2rem] border border-[#E4E0F5] bg-white p-8 shadow-sm">
          <h2 className="text-2xl font-semibold text-[#1D1B22]">Contact</h2>
          <p className="mt-3 text-sm leading-7 text-[#64607A]">
            For privacy-related questions or requests, contact us at privacy.meetiva.ai@gmail.com.
          </p>
          <Link
            to="/contact"
            className="mt-6 inline-flex text-sm font-semibold transition-colors"
            style={{ color: GRAD }}
          >
            Reach the team
          </Link>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPage;
